### PR TITLE
Release 1.0.0dev

### PR DESCRIPTION
**Pull request by ramprasadn**
## PR checklist

In this PR, 
1. I have removed everything related to cnvpytor including parameters, modules, subworkflows etc., 
2. Removed prepare_vcf.nf module.
3. Removed several TODO statements after converting them to issues.

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/raredisease/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/raredisease _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR> -stub`).
- [x] Ensure the test suite passes (`nextflow run . -profile test_one_sample,docker --outdir <OUTDIR> -stub`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [x] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [x] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by jemten — APPROVED** [review]
👍

**Comment by Gwennid** [comment]
I noticed we still load the HmtNote module even though we don't use it (in `https://github.com/genomic-medicine-sweden/raredisease/blob/1.0.0dev/subworkflows/local/mitochondria/merge_annotate_MT.nf`). Should we remove it entirely?

**Comment by ramprasadn** [comment]
Good catch Gwenna! I must have missed hmtnote somehow when I removed other unused modules from this PR. I will remove it now 👍🏻

**Comment by Gwennid** [comment]
Hello!
We had a suggestion for the credits, to underline that it was mostly a collaboration from the different Clinical Genomics nodes:
"Additional contributors were [Sima Rahimi](https://github.com/sima-r), [Gwenna Breton](https://github.com/Gwennid) and [Emma Västerviga](https://github.com/EmmaCAndersson) (Clinical Genomics Gothenburg); [Lauri Mesilaakso](https://github.com/ljmesi) (Clinical Genomics Linköping); [Subazini Thankaswamy Kosalai](https://github.com/sysbiocoder) (Clinical Genomics Örebro); [Annick Renevey](https://github.com/rannick) and [Peter Pruisscher](https://github.com/peterpru) (Clinical Genomics Stockholm); [Ryan Kennedy](https://github.com/ryanjameskennedy) (Clinical Genomics Lund); and [Lucas Taniguti](https://github.com/lmtani).
We thank the nf-core community for their extensive assistance in the development of this pipeline."

I wondered also whether we should cite MIP? (As the pipeline is very much based on it, and the MIP article has information about validation etc).

**Comment by jemten** [comment]
I think that sounds nice. We could even lead with saying something like this. Feel free to rephrase or weigh in.

> nf-core/raredisease was written in a collaboration between the Clinical Genomics nodes in Sweden, with major contributions from [Ramprasad Neethiraj](https://github.com/ramprasadn), [Anders Jemt](https://github.com/jemten), [Lucia Pena Perez](https://github.com/Lucpen), and [Mei Wu](https://github.com/projectoriented) at Clinical Genomics Stockholm.

> Additional contributors were [Sima Rahimi](https://github.com/sima-r), [Gwenna Breton](https://github.com/Gwennid) and [Emma Västerviga](https://github.com/EmmaCAndersson) (Clinical Genomics Gothenburg); [Lauri Mesilaakso](https://github.com/ljmesi) (Clinical Genomics Linköping); [Subazini Thankaswamy Kosalai](https://github.com/sysbiocoder) (Clinical Genomics Örebro); [Annick Renevey](https://github.com/rannick) and [Peter Pruisscher](https://github.com/peterpru) (Clinical Genomics Stockholm); [Ryan Kennedy](https://github.com/ryanjameskennedy) (Clinical Genomics Lund); and [Lucas Taniguti](https://github.com/lmtani).
We thank the nf-core community for their extensive assistance in the development of this pipeline.


If we want to we can reference MIP and the paper showing its use in healthcare. 
> Integration of whole genome sequencing into a healthcare setting: high diagnostic rates across multiple clinical entities in 3219 rare disease patients
Stranneheim H, Lagerstedt-Robinson K, Magnusson M, Kvarnung M, Nilsson D, Lesko N, Engvall M, Anderlid BM, Arnell H, Johansson CB, Barbaro M, Björck E, Bruhn H, Eisfeldt J, Freyer C, Grigelioniene G, Gustavsson P, Hammarsjö A, Hellström-Pigg M, Iwarsson E, Jemt A, Laaksonen M, Enoksson SL, Malmgren H, Naess K, Nordenskjöld M, Oscarson M, Pettersson M, Rasi C, Rosenbaum A, Sahlin E, Sardh E, Stödberg T, Tesi B, Tham E, Thonberg H, Töhönen V, von Döbeln U, Vassiliou D, Vonlanthen S, Wikström AC, Wincent J, Winqvist O, Wredenberg A, Ygberg S, Zetterström RH, Marits P, Soller MJ, Nordgren A, Wirta V, Lindstrand A, Wedell A.
Genome Med. 2021 Mar 17;13(1):40. doi: 10.1186/s13073-021-00855-5.
PMID: 33726816; PMCID: PMC7968334.

**Comment by Gwennid** [comment]
Should we add Peddy back to the documentation?

**Comment by jemten** [comment]
> Should we add Peddy back to the documentation?

If it's part of the release we should also have the documentation to match

**Pull request merged**
