### PR TITLE
input opt to required opt

### PR DESCRIPTION
**Pull request by projectoriented**
## PR checklist
`outdir` param is now required so refactored nextflow.config to reflect this

well previously there was a default `results/` but maybe it's better not to have one as it shows that if running on cloud this needs to have absolute path
- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/raredisease/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/raredisease _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR> -stub`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by jemten — COMMENTED** [review]
Cool, 
Maybe you can update this [line](https://github.com/nf-core/raredisease/blob/18c2d2a19508129a26cc7e601a7c58cefbb5f172/docs/usage.md?plain=1#L63) as well to reflect that the results directory isn't created per default.

**Comment by projectoriented** [comment]
@jemten Niice catch 🔍

**Comment by projectoriented** [comment]
note: this is also fixed in the nf-core pipeline template

**Review by jemten — APPROVED** [review]
Ace!

**Pull request merged**
