### PR TITLE
fix: parameters not resolving properly when igenomes are used

### PR DESCRIPTION
**Pull request by ramprasadn**
## PR checklist

Addresses https://nfcore.slack.com/archives/C04QR0T3G3H/p1709811356971549

Pretext: To illustrate the problem and the solution, I did a couple of test runs using the test config after setting ignore_igenomes to false. I also removed the bwa parameter from the nextflow.config, so we can see if it gets set to the value in igenomes.config.
 
Below is the list of resolved parameters as it enters the workflow in the current dev branch (notice the lack of bwa parameter in the list as it is not set anywhere).
```
        input:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/testdata/samplesheet_trio.csv
        genome:GRCh37
        igenomes_base:s3://ngi-igenomes/igenomes/
        igenomes_ignore:false
        local_genomes:null
        save_reference:false
        mito_name:MT
        analysis_type:wgs
        bait_padding:100
        run_rtgvcfeval:false
        save_mapped_as_cram:false
        skip_eklipse:false
        skip_fastp:true
        skip_fastqc:false
        skip_gens:true
        skip_germlinecnvcaller:true
        skip_haplocheck:false
        skip_peddy:true
        skip_me_annotation:false
        skip_mt_annotation:false
        skip_qualimap:false
        skip_snv_annotation:false
        skip_sv_annotation:false
        skip_mt_subsample:false
        skip_vcf2cytosure:false
        skip_vep_filter:false
        cadd_resources:null
        platform:illumina
        ngsbits_samplegender_method:xy
        fasta:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/reference.fasta
        fai:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/reference.fasta.fai
        bwamem2:null
        call_interval:null
        gcnvcaller_model:null
        gens_interval_list:null
        gens_pon_female:null
        gens_pon_male:null
        gens_gnomad_pos:null
        gnomad_af:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/gnomad_reformated.tab.gz
        gnomad_af_idx:null
        intervals_wgs:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/target_wgs.interval_list
        intervals_y:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/targetY.interval_list
        known_dbsnp:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/dbsnp_-138-.vcf.gz
        known_dbsnp_tbi:null
        mobile_element_references:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/mobile_element_references.tsv
        mobile_element_svdb_annotations:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/svdb_querydb_files.csv
        ml_model:https://s3.amazonaws.com/sentieon-release/other/SentieonDNAscopeModel1.0.model
        mt_fasta:null
        ploidy_model:null
        reduced_penetrance:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/reduced_penetrance.tsv
        readcount_intervals:null
        rtg_truthvcfs:null
        sample_id_map:null
        sequence_dictionary:null
        score_config_mt:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/rank_model_snv.ini
        score_config_snv:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/rank_model_snv.ini
        score_config_sv:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/rank_model_sv.ini
        sdf:null
        svdb_query_bedpedbs:null
        svdb_query_dbs:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/svdb_querydb_files.csv
        target_bed:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/target.bed
        variant_catalog:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/variant_catalog.json
        variant_consequences_snv:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/variant_consequences_v2.txt
        variant_consequences_sv:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/variant_consequences_v2.txt
        vep_filters:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/hgnc.txt
        vep_filters_scout_fmt:null
        vcf2cytosure_blacklist:null
        vcfanno_resources:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/vcfanno_resources.txt
        vcfanno_toml:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/vcfanno_config.toml
        vcfanno_lua:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/vcfanno_functions.lua
        vep_cache:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/vep_cache_and_plugins.tar.gz
        vep_plugin_files:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/vep_files.csv
        aligner:bwa
        min_trimmed_length:40
        mt_subsample_rd:150
        mt_subsample_seed:30
        rmdup:false
        cnvnator_binsize:1000
        variant_caller:deepvariant
        vep_cache_version:107
        sentieon_dnascope_pcr_indel_model:CONSERVATIVE
        variant_type:snp,indel
        multiqc_config:null
        multiqc_title:null
        multiqc_logo:null
        max_multiqc_email_size:25.MB
        multiqc_methods_description:null
        outdir:results
        publish_dir_mode:copy
        email:null
        email_on_fail:null
        plaintext_email:false
        monochrome_logs:false
        hook_url:null
        help:false
        version:false
        config_profile_name:Test profile
        config_profile_description:Minimal test dataset to check pipeline function
        custom_config_version:master
        custom_config_base:https://raw.githubusercontent.com/nf-core/configs/master
        config_profile_contact:null
        config_profile_url:null
        max_memory:6.GB
        max_cpus:2
        max_time:2.h
        validationFailUnrecognisedParams:false
        validation-fail-unrecognised-params:false
        validationLenientMode:false
        validation-lenient-mode:false
        validationSchemaIgnoreParams:genomes,igenomes_base
        validation-schema-ignore-params:genomes,igenomes_base
        validationShowHiddenParams:false
        validation-show-hidden-params:false
        validate_params:true

```

Resolved parameters as it enters the workflow after the fix (notice the presence of bwa parameter in the list, and it has resolved to the right version on igenomes).

```
        input:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/testdata/samplesheet_trio.csv
        genome:GRCh37
        igenomes_base:s3://ngi-igenomes/igenomes/
        igenomes_ignore:false
        local_genomes:null
        save_reference:false
        mito_name:MT
        analysis_type:wgs
        bait_padding:100
        run_rtgvcfeval:false
        save_mapped_as_cram:false
        skip_eklipse:false
        skip_fastp:true
        skip_fastqc:false
        skip_gens:true
        skip_germlinecnvcaller:true
        skip_haplocheck:false
        skip_peddy:true
        skip_me_annotation:false
        skip_mt_annotation:false
        skip_qualimap:false
        skip_snv_annotation:false
        skip_sv_annotation:false
        skip_mt_subsample:false
        skip_vcf2cytosure:false
        skip_vep_filter:false
        cadd_resources:null
        platform:illumina
        ngsbits_samplegender_method:xy
        aligner:bwa
        min_trimmed_length:40
        mt_subsample_rd:150
        mt_subsample_seed:30
        rmdup:false
        cnvnator_binsize:1000
        variant_caller:deepvariant
        vep_cache_version:107
        ml_model:https://s3.amazonaws.com/sentieon-release/other/SentieonDNAscopeModel1.0.model
        sentieon_dnascope_pcr_indel_model:CONSERVATIVE
        variant_type:snp,indel
        multiqc_config:null
        multiqc_title:null
        multiqc_logo:null
        max_multiqc_email_size:25.MB
        multiqc_methods_description:null
        outdir:results
        publish_dir_mode:copy
        email:null
        email_on_fail:null
        plaintext_email:false
        monochrome_logs:false
        hook_url:null
        help:false
        version:false
        config_profile_name:Test profile
        config_profile_description:Minimal test dataset to check pipeline function
        custom_config_version:master
        custom_config_base:https://raw.githubusercontent.com/nf-core/configs/master
        config_profile_contact:null
        config_profile_url:null
        max_memory:6.GB
        max_cpus:2
        max_time:2.h
        validationFailUnrecognisedParams:false
        validation-fail-unrecognised-params:false
        validationLenientMode:false
        validation-lenient-mode:false
        validationSchemaIgnoreParams:genomes,igenomes_base
        validation-schema-ignore-params:genomes,igenomes_base
        validationShowHiddenParams:false
        validation-show-hidden-params:false
        validate_params:true
        fai:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/reference.fasta.fai
        gnomad_af:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/gnomad_reformated.tab.gz
        intervals_wgs:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/target_wgs.interval_list
        intervals_y:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/targetY.interval_list
        known_dbsnp:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/dbsnp_-138-.vcf.gz
        mobile_element_references:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/mobile_element_references.tsv
        mobile_element_svdb_annotations:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/svdb_querydb_files.csv
        reduced_penetrance:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/reduced_penetrance.tsv
        score_config_mt:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/rank_model_snv.ini
        score_config_snv:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/rank_model_snv.ini
        score_config_sv:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/rank_model_sv.ini
        svdb_query_dbs:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/svdb_querydb_files.csv
        target_bed:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/target.bed
        variant_catalog:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/variant_catalog.json
        vcfanno_lua:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/vcfanno_functions.lua
        vcfanno_resources:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/vcfanno_resources.txt
        vcfanno_toml:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/vcfanno_config.toml
        variant_consequences_snv:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/variant_consequences_v2.txt
        variant_consequences_sv:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/variant_consequences_v2.txt
        vep_cache:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/vep_cache_and_plugins.tar.gz
        vep_filters:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/hgnc.txt
        vep_plugin_files:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/vep_files.csv
        fasta:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/reference.fasta
        bwa:s3://ngi-igenomes/igenomes//Homo_sapiens/Ensembl/GRCh37/Sequence/BWAIndex/version0.6.0/
        bwamem2:null
        call_interval:null
        gcnvcaller_model:null
        gens_interval_list:null
        gens_pon_female:null
        gens_pon_male:null
        gens_gnomad_pos:null
        gnomad_af_idx:null
        known_dbsnp_tbi:null
        mt_fasta:null
        ploidy_model:null
        readcount_intervals:null
        rtg_truthvcfs:null
        sample_id_map:null
        sequence_dictionary:null
        sdf:null
        svdb_query_bedpedbs:null
        vep_filters_scout_fmt:null
        vcf2cytosure_blacklist:null]
```

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/raredisease/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/raredisease _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test_one_sample,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by ramprasadn** [comment]
@maxulysse @nvnieuwk what do you guys think?

**Comment by nvnieuwk** [comment]
This does work if you work with and without igenomes? what if you supply a fasta from the cli or a params file?

**Comment by ramprasadn** [comment]
Yupe, works without igenomes as well. 

```
input:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/testdata/samplesheet_trio.csv
genome:GRCh37
igenomes_base:s3://ngi-igenomes/igenomes/
igenomes_ignore:true
local_genomes:null
save_reference:false
mito_name:MT
analysis_type:wgs
bait_padding:100
run_rtgvcfeval:false
save_mapped_as_cram:false
skip_eklipse:false
skip_fastp:true
skip_fastqc:false
skip_gens:true
skip_germlinecnvcaller:true
skip_haplocheck:false
skip_peddy:true
skip_me_annotation:false
skip_mt_annotation:false
skip_qualimap:false
skip_snv_annotation:false
skip_sv_annotation:false
skip_mt_subsample:false
skip_vcf2cytosure:false
skip_vep_filter:false
cadd_resources:null
platform:illumina
ngsbits_samplegender_method:xy
aligner:bwa
min_trimmed_length:40
mt_subsample_rd:150
mt_subsample_seed:30
rmdup:false
cnvnator_binsize:1000
variant_caller:deepvariant
vep_cache_version:107
ml_model:https://s3.amazonaws.com/sentieon-release/other/SentieonDNAscopeModel1.0.model
sentieon_dnascope_pcr_indel_model:CONSERVATIVE
variant_type:snp,indel
multiqc_config:null
multiqc_title:null
multiqc_logo:null
max_multiqc_email_size:25.MB
multiqc_methods_description:null
outdir:results
publish_dir_mode:copy
email:null
email_on_fail:null
plaintext_email:false
monochrome_logs:false
hook_url:null
help:false
version:false
config_profile_name:Test profile
config_profile_description:Minimal test dataset to check pipeline function
custom_config_version:master
custom_config_base:https://raw.githubusercontent.com/nf-core/configs/master
config_profile_contact:null
config_profile_url:null
max_memory:6.GB
max_cpus:2
max_time:2.h
validationFailUnrecognisedParams:false
validation-fail-unrecognised-params:false
validationLenientMode:false
validation-lenient-mode:false
validationSchemaIgnoreParams:genomes,igenomes_base
validation-schema-ignore-params:genomes,igenomes_base
validationShowHiddenParams:false
validation-show-hidden-params:false
validate_params:true
fasta:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/reference.fasta
fai:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/reference.fasta.fai
gnomad_af:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/gnomad_reformated.tab.gz
intervals_wgs:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/target_wgs.interval_list
intervals_y:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/targetY.interval_list
known_dbsnp:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/dbsnp_-138-.vcf.gz
mobile_element_references:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/mobile_element_references.tsv
mobile_element_svdb_annotations:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/svdb_querydb_files.csv
reduced_penetrance:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/reduced_penetrance.tsv
score_config_mt:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/rank_model_snv.ini
score_config_snv:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/rank_model_snv.ini
score_config_sv:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/rank_model_sv.ini
svdb_query_dbs:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/svdb_querydb_files.csv
target_bed:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/target.bed
variant_catalog:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/variant_catalog.json
vcfanno_lua:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/vcfanno_functions.lua
vcfanno_resources:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/vcfanno_resources.txt
vcfanno_toml:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/vcfanno_config.toml
variant_consequences_snv:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/variant_consequences_v2.txt
variant_consequences_sv:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/variant_consequences_v2.txt
vep_cache:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/vep_cache_and_plugins.tar.gz
vep_filters:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/hgnc.txt
vep_plugin_files:https://raw.githubusercontent.com/nf-core/test-datasets/raredisease/reference/vep_files.csv
genomes:[:]
bwa:null
bwamem2:null
call_interval:null
gcnvcaller_model:null
gens_interval_list:null
gens_pon_female:null
gens_pon_male:null
gens_gnomad_pos:null
gnomad_af_idx:null
known_dbsnp_tbi:null
mt_fasta:null
ploidy_model:null
readcount_intervals:null
rtg_truthvcfs:null
sample_id_map:null
sequence_dictionary:null
sdf:null
svdb_query_bedpedbs:null
vep_filters_scout_fmt:null
vcf2cytosure_blacklist:null
```

**Comment by nvnieuwk** [comment]
Awesome! seems like a good solution then!

**Comment by ramprasadn** [comment]
I haven't tested using a params file, but parameters resolve fine when you supply a parameter via cli. So I don't see a reason why it wouldn't work with a params file 😄

**Review by jemten — APPROVED** [review]

**Pull request merged**
