### PR TITLE
Metro map

### PR DESCRIPTION
**Pull request by hrydbeck**
Added a drawio metromap to docs/drawio

## PR checklist

- [*] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/raredisease/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/raredisease _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test_one_sample,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by jemten** [comment]
Hello @hrydbeck, 
looks like we need to update the eclint process to exclude the drawio file you added.
https://github.com/nf-core/raredisease/blob/c371602095ff83064f51747fe90dfc405ca7a864/.github/workflows/linting.yml#L25

**Comment by hrydbeck** [comment]
Hi,

Yes, I am not sure how to go about doing that, do you have a link with
information on how to do it or could we do it together or will you do it?
Maybe there is better way make a pull request for a single file? The file
is just a draft at the moment.

Cheers,

Halfdan

Den mån 11 sep. 2023 kl 11:23 skrev Anders Jemt ***@***.***>:

**Comment by jemten** [comment]
Added in #432 
You OK with closing this @hrydbeck?

**Comment by hrydbeck** [comment]
Yes, I am okey that. Maybe we can take a look at what has happened with Metromaps in a Wednesday meeting. Sorry have not been able to participate in the latest ones, but will return.

**Pull request closed without merging**
