### PR TITLE
refactoring clinical research split

### PR DESCRIPTION
**Pull request by jemten**
- Moves the split of a clinical and research list to an earlier step in the process. 
- Makes a small subworkflow of splitting clinical and research

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/raredisease/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/raredisease _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test_one_sample,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by ramprasadn** [comment]
Nice work! Output file documention needs to updated.. Other than that everything looks good 👍🏻

**Review by ramprasadn — APPROVED** [review]

**Review by ramprasadn — CHANGES_REQUESTED** [review]
Sorry! Approved by mistake

**Comment by jemten** [comment]
> Sorry! Approved by mistake

No worries, your comments have been adressed :)

**Review by ramprasadn — APPROVED** [review]
LGTM!

**Pull request merged**
