### PR TITLE
Documentation - Mandatory options for SNV annotation

### PR DESCRIPTION
**Pull request by fa2k**
I have added some information to the usage docs, while trying to get SNV annotation running:

* Move `--gnomad_af` from optional to mandatory parameters. If `--gnomad_af` is not used, the `BCFTOOLS_ROH` process is not run, and annotation is not performed. I also added information about the format of the `gnomad_af` file in the footnotes.
* Move `--score_config_snv` from optional to mandatory parameters. If this is missing, the `GENMOD_SCORE` process crashes.
* Add a footnote to `--vep_cache` that plugins can be installed, and `pLI` is mandatory (if no pLI, then `ADD_MOST_SEVERE_PLI` will crash).

I hope you can review this. I may have misinterpreted some things.
Issue #351.

## PR checklist

- [x] This comment contains a description of changes (with reason).
- [NA] If you've fixed a bug or added code that should be tested, add tests!
- [NA] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/raredisease/tree/master/.github/CONTRIBUTING.md)
- [NA] If necessary, also make a PR on the nf-core/raredisease _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [X] Make sure your code lints (`nf-core lint`).
- [NA] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [NA] Ensure the test suite passes (`nextflow run . -profile test_one_sample,docker --outdir <OUTDIR>`).
- [X] Usage Documentation in `docs/usage.md` is updated.
- [NA] Output Documentation in `docs/output.md` is updated.
- [NA] `CHANGELOG.md` is updated.
- [NA] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by ramprasadn** [comment]
Thanks for reporting this @fa2k. Good catch w.r.t gnomad_af file, and for making the vep setup of raredisease more clear in the usage docs. 

score_config_snv is used for ranking the variants and so it not required for annotation per se. But as the pipeline stands now, perhaps it just crashes at genmod score(?) and if so, that should be fixed. 😅 I believe it comes down to whether ranking step should be mandatory or optional. What do you think @jemten?

**Comment by jemten** [comment]
> Thanks for reporting this @fa2k. Good catch w.r.t gnomad_af file, and for making the vep setup of raredisease more clear in the usage docs.
> 
> score_config_snv is used for ranking the variants and so it not required for annotation per se. But as the pipeline stands now, perhaps it just crashes at genmod score(?) and if so, that should be fixed. 😅 I believe it comes down to whether ranking step should be mandatory or optional. What do you think @jemten?

Hmm, I agree it's not very elegant to simply crash. If genmod is part of the standard annotation workflow, controlled by the `--skip_snv_annotation` and `--skip_sv_annotation` options then it should be added as a mandatory file here https://github.com/nf-core/raredisease/blob/06492aba0273a2096611a5fcd15466f077607257/workflows/raredisease.nf#L75

We could add an ext.when statement to the config. Let's discuss today how to proceed.

**Comment by ramprasadn** [comment]
Think its best to incorporate these changes as such for now. Best to modify the feature to make it more customizable in the next feature. 😄

**Review by ramprasadn — APPROVED** [review]
LGTM

**Pull request merged**
