### PR TITLE
Change hardcoded platform value to params.platform in modules/align_MT.config

### PR DESCRIPTION
**Pull request by alkc**
Tiny update that sets a hardcoded platform value in the `ALIGN_MT.config` to use `params.platform` instead. 

Compare with the config for the equivalent ALIGN_MT_SHIFT process:

https://github.com/nf-core/raredisease/blob/a2e6812d6953a81800d42490ad2ec11c83224603/conf/modules/align_MT.config#L89-L97

## PR checklist

- [X] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/raredisease/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/raredisease _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test_one_sample,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by jemten — APPROVED** [review]
Good catch @alkc!

**Review by ramprasadn — CHANGES_REQUESTED** [review]
Should be changed here as well? https://github.com/nf-core/raredisease/blob/a2e6812d6953a81800d42490ad2ec11c83224603/conf/modules/align_MT.config#L45

**Comment by alkc** [comment]
> Should be changed here as well?
> 
> https://github.com/nf-core/raredisease/blob/a2e6812d6953a81800d42490ad2ec11c83224603/conf/modules/align_MT.config#L45

That's the line changed by this PR! 

See: https://github.com/nf-core/raredisease/pull/475/commits/0809a4083e7f7e28ff2476a639f7bd0f73aa46ce

**Comment by ramprasadn** [comment]
Gah.. sorry! My brain had a paralysis 😅

**Review by ramprasadn — APPROVED** [review]

**Pull request merged**
