### PR TITLE
Add option to restrict analysis to specific contigs

### PR DESCRIPTION
**Pull request by ramprasadn**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/raredisease/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/raredisease _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test_one_sample,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by fellen31** [comment]
In long-reads I imagine this strategy would not call translocations with one good breakpoint in an interesting gene on 1-22, X, Y and the other breakpoint mapping to a few different places (including unplaced contigs). 

Would this be an issue here?

**Comment by ramprasadn** [comment]
Hi Felix! We have added the option to restrict the analysis to chromosomes only because alignments to unplaced contigs can be messy, leading to less reliable results. We want to minimize any potential errors from those alignments.

**Review by fellen31 — COMMENTED** [review]
Could you add to the usage documentation?

Otherwise it looks good to me. I'd lean towards using a BED-file rather than a regions string, but both work.

**Comment by fellen31** [comment]
> Hi Felix! We have added the option to restrict the analysis to chromosomes only because alignments to unplaced contigs can be messy, leading to less reliable results. We want to minimize any potential errors from those alignments.

Makes sense to not deal with such variants at all, thanks for clarifying!

**Review by fellen31 — APPROVED** [review]
👍

**Pull request merged**
