### PR TITLE
Add a new sample field to meta

### PR DESCRIPTION
**Pull request by ramprasadn**
## PR checklist

We used to add "_T[linenumber]" to sample id to differentiate between data from different lanes. Then before merging bam files from multiple lanes into one file, we split based on "_T" to get the sample id back. This could potentially cause issues when the sample name has an _T. To avoid that, I have created a new field `sample` in the meta which also contains the user given sample id. Before the merging step the value from the sample field will be copied into id. 

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/raredisease/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/raredisease _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test_one_sample,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by asp8200** [comment]
Damn! "no space left on device."!
```
Command error:
  Unable to find image 'quay.io/biocontainers/hmtnote:0.7.2--pyhdfd78af_1' locally
  0.7.2--pyhdfd78af_1: Pulling from biocontainers/hmtnote
  c1a16a04cedd: Already exists
  4ca545ee6d5d: Already exists
  8c4452938393: Pulling fs layer
  8c4452938393: Verifying Checksum
  8c4452938393: Download complete
  docker: failed to register layer: mkdir /usr/local/lib/python3.10/site-packages/pomegranate-0.14.8.dist-info: no space left on device.
  ```

**Comment by ramprasadn** [comment]
Yeah, I guess I have to start thinking about turning off some of the process for the github ci, so that we can avoid this error 😅

**Comment by ramprasadn** [comment]
mt_analysis uses a few large containers so I have turned it off to save space in the runner. But I haven't turned it off for the `test_one_sample` profile so at least we are testing that workflow partially.

Hopefully, we can switch to nf-test and all these issues will go away 😅

**Review by jemten — APPROVED** [review]
Looks good to me! Nice to not rely on string splitting to get the sample id.

**Pull request merged**
