### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by ramprasadn**
## PR checklist

Address #593

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/raredisease/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/raredisease _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test_one_sample,docker --outdir <OUTDIR>`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by fellen31 — COMMENTED** [review]
Are all the mandatory plugin files not supplied with `--vep_cache`? If so, does it really need to be mandatory, or could you add? 
```
    } else {
        ch_vep_extra_files = Channel.value([])
    }
``` 

Otherwise, should It be added to `mandatoryParams` as well?

**Comment by ramprasadn** [comment]
Plugin files don't have to supplied with vep_cache. It used to be set up that way because it made it easier for nextflow to stage those files, but we no longer use that approach. There are some plugin files that come bundled with cache (ex: pli), but not all.  For instance, we use custom plugins for annotations, and those are not part of vep's cache.

**Comment by fellen31** [comment]
> There are some plugin files that come bundled with cache (ex: pli), but not all. For instance, we use custom plugins for annotations, and those are not part of vep's cache.

Ah, I did not realise pli was bundled with the cache, I thought that was downloaded separately.

**Comment by ramprasadn** [comment]
You are right, that was my memory failing me. We get that file from https://github.com/Ensembl/VEP_plugins 😅 Then I suppose at least for all of the plugins we use, the data doesn't come bundled with cache.

**Comment by fellen31** [comment]
Yes, asking because I need to add the `--vep_plugin_files` parameter as well: https://github.com/genomic-medicine-sweden/nallo/pull/314 😃

**Comment by ramprasadn** [comment]
aah.. well timed PR 😄

**Review by fellen31 — APPROVED** [review]
I think, in the test profile these:
```
LoFtool_scores.txt
pLI_values_107.txt
spliceai_21_scores_raw_indel_-v1.3-.vcf.gz
spliceai_21_scores_raw_indel_-v1.3-.vcf.gz.tbi
spliceai_21_scores_raw_snv_-v1.3-.vcf.gz
spliceai_21_scores_raw_snv_-v1.3-.vcf.gz.tbi
```

 are currently provided to VEP both through `--vep_cache` with `vep_cache_and_plugins.tar.gz` _and_ with `--vep_plugin_files` with [vep_files.csv](https://github.com/nf-core/test-datasets/blob/raredisease/reference/vep_files.csv)

However, 

```
pLI.pm
SpliceAI.pm
```
are provided only in `vep_cache_and_plugins.tar.gz`. If you were to provide with with `--vep_plugin_files` instead, these would end up in a flat structure directly in the base of the work directory, i.e. as 

```
./pLI.pm
./SpliceAI.pm
```
and not 
```
./vep_cache/Plugins/pLI.pm
./vep_cache/Plugins/SpliceAI.pm
```

If you think it's necessary, could you double check that VEP picks up ./pLI.pm and ./SpliceAI.pm even though `--dir_plugins vep_cache/Plugins` is specified? 

Or are they not needed at all because VEP picks up `/usr/local/share/ensembl-vep-110.0-0/pLI.pm` from within the docker image, and not the the one supplied by the pipeline?

I'm not 100% sure how to tell, or if it's important. Bit of a rabbit hole trying to understand what is needed and not for nallo 😄 

I'll approve, but maybe consider updating the docs and/or testdata to reflect this?

**Comment by ramprasadn** [comment]
> I think, in the test profile these:
> 
> ```
> LoFtool_scores.txt
> pLI_values_107.txt
> spliceai_21_scores_raw_indel_-v1.3-.vcf.gz
> spliceai_21_scores_raw_indel_-v1.3-.vcf.gz.tbi
> spliceai_21_scores_raw_snv_-v1.3-.vcf.gz
> spliceai_21_scores_raw_snv_-v1.3-.vcf.gz.tbi
> ```
> 
> are currently provided to VEP both through `--vep_cache` with `vep_cache_and_plugins.tar.gz` _and_ with `--vep_plugin_files` with [vep_files.csv](https://github.com/nf-core/test-datasets/blob/raredisease/reference/vep_files.csv)

vep_cache_and_plugins.tar.gz file was generated way back when there were no option to feed plugins files seperately so as a roundabout way we packaged the plugins alongside cache. Now even though we have moved to supplying plugin files seperately, we are still using the same file hence the discrepancy. 😄 

But I would guess if the files end up in the main working directory and if plugin directory is specified in the command line, it should run the ones found in plugin directory. I am not 100% sure how to tell either.. last time I looked into this, I remember coming out more confused. Need to do a proper investigation sometime soon. 😄

**Pull request merged**
